import 'package:flutter/material.dart';

TextTheme appMaterialTallTheme = const TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'tall displayLarge',
    inherit: false,
    fontSize: 112.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.alphabetic,
  ),
  displayMedium: TextStyle(
    debugLabel: 'tall displayMedium',
    inherit: false,
    fontSize: 56.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  displaySmall: TextStyle(
    debugLabel: 'tall displaySmall',
    inherit: false,
    fontSize: 45.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineLarge: TextStyle(
    debugLabel: 'tall headlineLarge',
    inherit: false,
    fontSize: 40.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineMedium: TextStyle(
    debugLabel: 'tall headlineMedium',
    inherit: false,
    fontSize: 34.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineSmall: TextStyle(
    debugLabel: 'tall headlineSmall',
    inherit: false,
    fontSize: 24.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  titleLarge: TextStyle(
    debugLabel: 'tall titleLarge',
    inherit: false,
    fontSize: 24.0,
    fontWeight: FontWeight.w700,
    textBaseline: TextBaseline.ideographic,
  ),
  titleMedium: TextStyle(
    debugLabel: 'tall titleMedium',
    inherit: false,
    fontSize: 21.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  titleSmall: TextStyle(
    debugLabel: 'tall titleSmall',
    inherit: false,
    fontSize: 17.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  bodyLarge: TextStyle(
    debugLabel: 'tall bodyLarge',
    inherit: false,
    fontSize: 15.0,
    fontWeight: FontWeight.w700,
    textBaseline: TextBaseline.ideographic,
  ),
  bodyMedium: TextStyle(
    debugLabel: 'tall bodyMedium',
    inherit: false,
    fontSize: 15.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  bodySmall: TextStyle(
    debugLabel: 'tall bodySmall',
    inherit: false,
    fontSize: 13.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  labelLarge: TextStyle(
    debugLabel: 'tall labelLarge',
    inherit: false,
    fontSize: 15.0,
    fontWeight: FontWeight.w700,
    textBaseline: TextBaseline.ideographic,
  ),
  labelMedium: TextStyle(
    debugLabel: 'tall labelMedium',
    inherit: false,
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  labelSmall: TextStyle(
    debugLabel: 'tall labelSmall',
    inherit: false,
    fontSize: 11.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
);
