name: jam
description: "Jam. Joint Activity Meetup."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  annotations:
    path: ../annotations
  audioplayers: ^5.2.1
  bugsnag_flutter: ^3.0.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter:
    sdk: flutter
  flutter_circle_color_picker: null
  flutter_contacts: null
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.4
  flutter_local_notifications: null
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  geobase: ^1.0.0
  geolocator: ^10.1.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.6.2
  google_sign_in: ^6.2.1
  hive: null
  hive_flutter: null
  hooks_riverpod: ^2.4.9
  image: ^4.1.7
  image_picker: ^1.0.7
  jam_theme:
    path: ../jam_theme
  jam_ui:
    path: ../jam_ui
  jam_utils:
    path: ../jam_utils
  js: ^0.6.7
  json_annotation: null
  just_audio: ^0.9.36
  omni_datetime_picker: ^1.0.9
  permission_handler: null
  powersync: ^1.2.2
  powersync_attachments_helper: ^0.2.1
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  share_plus: null
  # auto_size_text: null <<< causes segfault in debug

  # removed for demo

  # record_mp3: ^3.0.0
  # shared_preferences: ^2.2.2
  # shared_preferences_android: ^2.2.1
  # shared_preferences_ios: 2.1.1
  # shared_preferences_platform_interface: ^2.3.2
  # shared_preferences_web: ^2.2.2
  # webcrypto: ^0.5.4
  # voice_message_package: ^2.1.4
  supabase_flutter: ^2.2.0
  uuid: ^4.3.3
  visibility_detector: ^0.4.0+2
  yjy_google_maps_flutter_platform_interface: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # Domain specific package for generating data models
  freezed: ^2.4.6
  generators:
    path: ../generators
  # local database
  hive_generator: null
  json_serializable: ^6.7.1
  # State management generator & linter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/data/
    - .env
flutter_intl:
  enabled: true
