final class EnvironmentConstants {
  static const SUPABASE_PROJECT_URL = 'SUPABASE_PROJECT_URL';
  static const SUPABASE_API_KEY = 'SUPABASE_API_KEY';
  static const GOOGLE_OAUTH_CLIENT_ID_ANDROID =
      'GOOGLE_OAUTH_CLIENT_ID_ANDROID';
  static const GOOGLE_OAUTH_CLIENT_ID_IOS = 'GOOGLE_OAUTH_CLIENT_ID_IOS';
  static const GOOGLE_OAUTH_CLIENT_ID_WEB = 'GOOGLE_OAUTH_CLIENT_ID_WEB';
  static const BUGSNAG_API_KEY = 'BUGSNAG_API_KEY';
  static const POWERSYNC_INSTANCE_URL = 'POWERSYNC_INSTANCE_URL';
  static const MAP_STYLE_PATH = 'assets/data/map_style.json';

  static const PASSWORD_RESET_MAGIC_LINK = 'PASSWORD_RESET_MAGIC_LINK';
}
