const String LICENSE = '''
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed condimentum elit sit amet ligula malesuada pellentesque. Nullam vitae dolor vitae sapien sagittis luctus at vitae eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam maximus leo nec ante laoreet consectetur at sed nibh. Pellentesque vitae orci quis neque luctus bibendum eget ac purus. Quisque non justo turpis. Suspendisse convallis eu velit a malesuada. Vestibulum pharetra est at tincidunt porttitor. Integer condimentum risus sed risus volutpat vulputate at facilisis eros. Sed accumsan mauris tortor. Nunc semper iaculis arcu a cursus. Ut vitae ipsum vestibulum, pharetra dolor id, malesuada libero. Praesent arcu arcu, viverra nec metus eget, feugiat commodo leo. Sed feugiat commodo tellus, in elementum nisl. \n

Quisque efficitur ligula mi, quis rhoncus purus luctus sed. Donec id lectus nec lorem mollis maximus porta sed arcu. Nulla facilisi. Donec eget mauris placerat, varius velit ut, porttitor leo. Donec lobortis orci ac felis luctus rhoncus. Cras vel tristique leo. Mauris auctor magna a nulla faucibus tincidunt. Ut interdum sapien tortor, in dapibus sapien bibendum in. \n

Sed eleifend lacinia mauris, a auctor erat hendrerit sed. In finibus tellus eget dui tristique, fringilla sagittis quam facilisis. Quisque eget mi sed ex ornare consectetur. Suspendisse a sagittis elit. Nulla facilisi. Nullam imperdiet ullamcorper nisl, nec efficitur neque tempus a. Aliquam erat volutpat. Vivamus a dignissim massa. Vivamus tempus massa ipsum, sit amet finibus sem ornare sit amet. Sed rutrum lacinia nulla vel lacinia. Curabitur sollicitudin nulla urna, sit amet condimentum lacus placerat eu. Nullam euismod eget arcu quis dapibus. Praesent vulputate porta metus sed eleifend. \n

Etiam consequat et lorem ac eleifend. In ornare turpis nisl, ac faucibus lacus imperdiet ultrices. Mauris commodo libero massa, at vehicula libero fringilla non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vehicula dolor ac ex suscipit dignissim. Phasellus feugiat augue id consectetur suscipit. Pellentesque sagittis purus non mauris pretium consequat. In turpis nibh, interdum non ligula in, pharetra finibus nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. \n

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque eget neque odio. Donec eget orci aliquam, pretium nulla ac, porta turpis. Nulla facilisi. Nunc eu tellus neque. Nam vehicula purus felis. Quisque ut nibh turpis. Curabitur accumsan sapien vitae rhoncus congue. Praesent in lorem ac tellus sollicitudin venenatis quis ut ex. Suspendisse venenatis, purus non sagittis feugiat, sem libero bibendum mauris, quis aliquet sem risus sit amet sem. Nam neque mauris, bibendum in erat in, maximus ullamcorper orci. Quisque varius mi at lectus eleifend semper. Vivamus hendrerit mattis ante, id fermentum lectus faucibus id. \n

 ''';
